"""baseline operational schema

Revision ID: aa3e20503f2b
Revises:
Create Date: 2026-09-10 12:31:55.183287
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "aa3e20503f2b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "close_decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("decision_hash", sa.String(length=64), nullable=False),
        sa.Column("reconciliation_run_key", sa.String(length=64), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("policy_hash", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("accepted_count", sa.Integer(), nullable=False),
        sa.Column("accepted_value_paise", sa.Integer(), nullable=False),
        sa.Column("matched_count", sa.Integer(), nullable=False),
        sa.Column("matched_value_paise", sa.Integer(), nullable=False),
        sa.Column("pending_count", sa.Integer(), nullable=False),
        sa.Column("pending_value_paise", sa.Integer(), nullable=False),
        sa.Column("unresolved_count", sa.Integer(), nullable=False),
        sa.Column("unresolved_value_paise", sa.Integer(), nullable=False),
        sa.Column("quarantined_count", sa.Integer(), nullable=False),
        sa.Column("control_failure_count", sa.Integer(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("decision_hash"),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_key", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_key"),
    )
    op.create_table(
        "reconciliation_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_key", sa.String(length=64), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("rule_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_key"),
    )
    op.create_table(
        "source_identities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("batch_id", sa.String(length=128), nullable=False),
        sa.Column("record_id", sa.String(length=128), nullable=False),
        sa.Column("partner_code", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source", "batch_id", "record_id", name="uq_source_identity"
        ),
    )
    op.create_table(
        "close_blockers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("close_decision_id", sa.Integer(), nullable=False),
        sa.Column("blocker_type", sa.String(length=32), nullable=False),
        sa.Column("reference", sa.String(length=160), nullable=False),
        sa.Column("amount_paise", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence_reference", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["close_decision_id"],
            ["close_decisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "delivery_controls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ingestion_run_id", sa.Integer(), nullable=False),
        sa.Column("delivery_key", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("artifact_hash", sa.String(length=64), nullable=False),
        sa.Column("manifest_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("total_amount_paise", sa.Integer(), nullable=True),
        sa.Column("quarantined_count", sa.Integer(), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("evidence_path", sa.String(length=512), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("delivery_key"),
    )
    op.create_table(
        "reconciliation_decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("business_event_id", sa.String(length=128), nullable=False),
        sa.Column("partner_code", sa.String(length=64), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("amount_paise", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("rule_version", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["reconciliation_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_id", "business_event_id", name="uq_run_business_event"
        ),
    )
    op.create_index(
        op.f("ix_reconciliation_decisions_partner_code"),
        "reconciliation_decisions",
        ["partner_code"],
        unique=False,
    )
    op.create_table(
        "source_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identity_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("artifact_hash", sa.String(length=64), nullable=False),
        sa.Column("source_location", sa.String(length=256), nullable=False),
        sa.Column("validation_state", sa.String(length=32), nullable=False),
        sa.Column("is_selected", sa.Boolean(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["source_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identity_id", "payload_hash", name="uq_identity_payload"),
        sa.UniqueConstraint("identity_id", "version", name="uq_identity_version"),
    )
    op.create_table(
        "canonical_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_version_id", sa.Integer(), nullable=False),
        sa.Column("source_system", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("source_record_id", sa.String(length=128), nullable=False),
        sa.Column("business_event_id", sa.String(length=128), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column("partner_code", sa.String(length=64), nullable=False),
        sa.Column("batch_id", sa.String(length=128), nullable=False),
        sa.Column("loan_id", sa.String(length=128), nullable=True),
        sa.Column("customer_surrogate_id", sa.String(length=128), nullable=True),
        sa.Column("partner_loan_reference", sa.String(length=128), nullable=True),
        sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reconciliation_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("amount_paise", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("source_status", sa.String(length=32), nullable=False),
        sa.Column("canonical_status", sa.String(length=32), nullable=False),
        sa.Column("related_event_reference", sa.String(length=128), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("artifact_hash", sa.String(length=64), nullable=False),
        sa.Column("source_location", sa.String(length=512), nullable=False),
        sa.Column("record_state", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_version_id"], ["source_versions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_version_id", name="uq_canonical_source_version"),
    )
    op.create_index(
        op.f("ix_canonical_records_batch_id"),
        "canonical_records",
        ["batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_canonical_records_correlation_id"),
        "canonical_records",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_canonical_records_partner_code"),
        "canonical_records",
        ["partner_code"],
        unique=False,
    )
    op.create_table(
        "conflict_resolutions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identity_id", sa.Integer(), nullable=False),
        sa.Column("selected_version_id", sa.Integer(), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.String(length=512), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["source_identities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["selected_version_id"],
            ["source_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exceptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exception_id", sa.String(length=36), nullable=False),
        sa.Column("business_event_id", sa.String(length=128), nullable=False),
        sa.Column("latest_decision_id", sa.Integer(), nullable=False),
        sa.Column("classification", sa.String(length=32), nullable=False),
        sa.Column("amount_paise", sa.Integer(), nullable=False),
        sa.Column("partner_code", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.String(length=32), nullable=False),
        sa.Column("owner", sa.String(length=128), nullable=False),
        sa.Column("assignee", sa.String(length=128), nullable=True),
        sa.Column("recommended_action", sa.Text(), nullable=False),
        sa.Column("escalation_path", sa.String(length=256), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sla_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_requested_by", sa.String(length=128), nullable=True),
        sa.Column("material_override", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["latest_decision_id"],
            ["reconciliation_decisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exception_id"),
        sa.UniqueConstraint(
            "partner_code", "business_event_id", name="uq_exception_partner_event"
        ),
    )
    op.create_index(
        op.f("ix_exceptions_partner_code"), "exceptions", ["partner_code"], unique=False
    )
    op.create_table(
        "reconciliation_decision_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("decision_id", sa.Integer(), nullable=False),
        sa.Column("source_version_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["reconciliation_decisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["reconciliation_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["source_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "source_version_id", name="uq_run_source_member"),
    )
    op.create_table(
        "exception_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exception_record_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("actor_role", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("before_status", sa.String(length=32), nullable=True),
        sa.Column("after_status", sa.String(length=32), nullable=False),
        sa.Column("before_assignee", sa.String(length=128), nullable=True),
        sa.Column("after_assignee", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["exception_record_id"],
            ["exceptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exception_evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exception_record_id", sa.Integer(), nullable=False),
        sa.Column("decision_id", sa.Integer(), nullable=False),
        sa.Column("source_version_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["reconciliation_decisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exception_record_id"],
            ["exceptions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["source_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "exception_record_id",
            "decision_id",
            "source_version_id",
            name="uq_exception_decision_evidence",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exception_evidence")
    op.drop_table("exception_actions")
    op.drop_table("reconciliation_decision_members")
    op.drop_index(op.f("ix_exceptions_partner_code"), table_name="exceptions")
    op.drop_table("exceptions")
    op.drop_table("conflict_resolutions")
    op.drop_index(
        op.f("ix_canonical_records_partner_code"), table_name="canonical_records"
    )
    op.drop_index(
        op.f("ix_canonical_records_correlation_id"), table_name="canonical_records"
    )
    op.drop_index(op.f("ix_canonical_records_batch_id"), table_name="canonical_records")
    op.drop_table("canonical_records")
    op.drop_table("source_versions")
    op.drop_index(
        op.f("ix_reconciliation_decisions_partner_code"),
        table_name="reconciliation_decisions",
    )
    op.drop_table("reconciliation_decisions")
    op.drop_table("delivery_controls")
    op.drop_table("close_blockers")
    op.drop_table("source_identities")
    op.drop_table("reconciliation_runs")
    op.drop_table("ingestion_runs")
    op.drop_table("close_decisions")
    # ### end Alembic commands ###
